--- 
title: "Learning Physics Through Simulation for High Schoolers"
subtitle: "spm-physics books"
author: "Mei Ling"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apa
csl: include/apa.csl
link-citations: yes
description: "Textbook on Physics for SPM students"
url: "https://sohmeiling.github.io/Physics-SPM"
github-repo: "sohmeiling/Physics-SPM"

---

```{r cite-packages, include = FALSE}
# automatically create a bib database for R packages
# add any packages you want to cite here
knitr::write_bib(c(
  .packages(), 'bookdown', 'tidyverse', 'kableExtra'
), 'packages.bib')


```


# Overview {-}

This textbook is written for students affected by the online learning. The overaching goal is to aid the students in learning concepts and experiments in Science through illustrations, simulation, and videos.

Unlike other textbooks you may have encountered, this is an **interactive textbook**. Each chapter contains embedded exercises as well as web applications to help students better understand the content. The interactive content will only work if you access this material through a web browser. Printing out the material is not recommended. If you want to access the textbook without an internet connection or have a local version to keep in case this site changes or moves, you can [download a version for offline use](#offline-textbook.zip). Just extract the files from the ZIP archive, locate the file `index.html` in the `docs` directory, and open this file using a web browser.

## How to cite this book {-}


## ## Found an issue? {-}

If you find errors or typos, have questions or suggestions, please file an issue at <https://github.com/sohmeiling/Physics-SPM/issues>. Thanks!

## Information for educators {-}

You are free to re-use and modify the material in this textbook for your own purposes, with the stipulation that you **cite** the original work. Please note additional terms of the [Creative Commons CC-BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) governing re-use of this material.

The book was built using the R [**`bookdown`**](https://bookdown.org) package. This output format is built with Bootstrap, using carefully crafted features to provide a clean reading experience whether you are on a phone, tablet, or desktop. To read more about this format, see: https://bookdown.org/yihui/bookdown/html.html#bootstrap4-style. 

The source files are available at [github](https://github.com/sohmeiling/Physics-SPM).